export const PACKAGE_DATA_LOADING = "PACKAGE_DATA_LOADING";
export const PACKAGE_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const PACKAGE_DATA_FAILURE = 'PACKAGE_DATA_FAILURE';


export const USER_DATA_LOADING = "USER_DATA_LOADING";
export const USER_DATA_SUCCESS = 'USER_DATA_SUCCESS';
export const USER_DATA_FAILURE = 'USER_DATA_FAILURE';


export const HOTEL_DATA_LOADING = "HOTEL_DATA_LOADING";
export const HOTEL_DATA_SUCCESS = 'HOTEL_DATA_SUCCESS';
export const HOTEL_DATA_FAILURE = 'HOTEL_DATA_FAILURE';


export const HOTEL_DETAILS_DATA_LOADING = "HOTEL_DETAILS_DATA_LOADING";
export const HOTEL_DETAILS_DATA_SUCCESS = 'HOTEL_DETAILS_DATA_SUCCESS';
export const HOTEL_DETAILS_DATA_FAILURE = 'HOTEL_DETAILS_DATA_FAILURE';


export const HOTEL_BOOKING_DETAILS_DATA_LOADING = "HOTEL_BOOKING_DETAILS_DATA_LOADING";
export const HOTEL_BOOKING_DETAILS_DATA_SUCCESS = 'HOTEL_BOOKING_DETAILS_DATA_SUCCESS';
export const HOTEL_BOOKING_DETAILS_DATA_FAILURE = 'HOTEL_BOOKING_DETAILS_DATA_FAILURE';

export const PACKAGE_BOOKING_DETAILS_DATA_LOADING = "PACKAGE_BOOKING_DETAILS_DATA_LOADING";
export const PACKAGE_BOOKING_DETAILS_DATA_SUCCESS = 'PACKAGE_BOOKING_DETAILS_DATA_SUCCESS';
export const PACKAGE_BOOKING_DETAILS_DATA_FAILURE = 'PACKAGE_BOOKING_DETAILS_DATA_FAILURE';


export const QUERY_DATA_LOADING = "QUERY_DATA_LOADING";
export const QUERY_DATA_SUCCESS = 'QUERY_DATA_SUCCESS';
export const QUERY_DATA_FAILURE = 'QUERY_DATA_FAILURE';

export const WIDTH_DATA_LOADING = "WIDTH_DATA_LOADING";
export const WIDTH_DATA_SUCCESS = 'WIDTH_DATA_SUCCESS';
export const WIDTH_DATA_FAILURE = 'WIDTH_DATA_FAILURE';